### ISSUE TITLE
update Announcements (send emails and allow links)

### ISSUE THREAD

**Issue by JohnRamberger** [JohnRamberger/dsgt-member-portal#20]
## Read through all before working, lots of overlap. Ex: only make 1 knex migration.
# Part 1 -- sending emails
We want announcements to send an email to all active members on the portal. Make sure that your implementation follows the checklist below:
- [x] Do not send emails to every single person individually (emails to send are not unique). Instead, send one email with all of the emails in the BCC (important!!!).
- [x] Only send emails to members who are active (for now just check `enabled`) AND who have `not` opted out of emails. Ask John for more info!
- [x] include a checkbox when sending an announcement to email members (this way we can choose whether to send the email).
- [x] use a simple email template that works for any announcement. 

This is an example of how I would go about doing this (ignore order):
- [x] (frontend) create an email template that is only missing the announcement message. Don't forget to decide on a subject line for the email as well. (Get this template approved by John!)
- [x] (frontend) create a checkbox on the announcement page to allow us to send the email. (send this value when creating the announcement)
- [x] (backend) when creating an announcement (API), first make sure you need to send an email. if so, get a list of members that have active accounts. Then, send an email through the email-sending script. Ask John for help!
- [x] (backend) add a new column in the announcement table to keep track of whether an email has been sent (use a knex migration to edit schema). The default value of this column should be false. Ask John for help!

# Part 2 -- allow links (and link message)
we want to allow announcements to have a link (so that users can follow up the announcement). When sending an announcement, include a field with a URL to a link. Also include a field for the message of the link. 
Ex: a button that says "Learn More" and links to URL1. the link would be URL1 and the message of the link is "Learn More"
Do the following:

- [x] update schema for announcements to include links and link messages. (Update the schema with the previous part as well -- email sent)
- [x] add fields to input URL and message on announcement page (BOTH fields are optional!). If given a link and no link message, set the default message to "Learn More"
- [x] update API endpoint to allow link and link message (include these values in DB)
- [x] update the react component for announcements to show the link (which is optional) as a button with the message as the text. Make sure to have this used on the announcement page as the preview.
